name: briggsadv
favicon: null
layout_spectrum: 0.509901390876621
typography_spectrum: 0.44536804989911616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0c423'
    - '#ffffff'
    - '#e2c834'
    - '#fbf9e7'
    - '#e1c62b'
  brandStrength: 0.9500095094554126
  lightness: 0.567499901400879
  saturation: 0.09928128635510802
  rhythmicContrast: 0.25
purpose: []
