name: briggsadv
favicon: null
layout_spectrum: 0.509901390876621
typography_spectrum: 0.44536804989911616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9500095094554126
  lightness: 0.567499901400879
  saturation: 0.09928128635510802
  rhythmicContrast: 0.0606092088855803
purpose: []
